version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - gradle clean
      - gradle bootJar
      -
artifacts:
  files:
    - Dockerfile
    - build/libs/familytalk-0.0.1.jar
    - .ebextensions/**/*

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::936701173831:role/service-role/codebuild-team7wp-service-role
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/standard:2.0
  Timeout: 60