version: 0.2

phases:
  pre_build:
    commands:
      - echo [PHASE] Entered the pre_build phase...
      - chmod +x ./gradlew

  build:
    commands:
      - ./gradlew clean
      - ./gradlew bootJar

artifacts:
  name: wp-famillytalk-$(date +%Y-%m-%d-%H:%m:%S)
  files:
    - appspec.yml
    - Dockerfile
    - build/libs/*.jar

cache:
  paths:
    - '/root/.gradle/caches/**/*'