version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo [PHASE] Entered the install phase...

  build:
    commands:
      - echo [PHASE] Entered the build phase...
      - gradle clean
      - gradle bootJar

artifacts:
  name: wp-famillytalk-$(date +%Y-%m-%d-%H:%m:%S)
  type: zip
  files:
    - appspec.yml
    - Dockerfile
    - build/libs/*.jar

cache:
  paths:
    - '/root/.gradle/caches/**/*'
