spring:
  profiles:
    active: local
  main:
    web-application-type: reactive
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

password:
  encoder:
    secret: mysecret
    iteration: 33
    keylength: 256

jjwt:
  secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
  expiration: 288000000

api:
  news:
    token: cad159957eba4f1da3adc1bbb21de063
  weather:
    token: 69143ac081ec9450b8b29d5f508e658a

server:
  error:
    whitelabel:
      enabled: false

#logging:
#  level:
#    .: error
#    org.springframework: ERROR
#    com.warmup.familytalk: INFO
#
#debug: true
---

spring:
  profiles: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/familytalk
    username: depromeet
    password: pass

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    jdbc:
      lob:
        non_contextual_creation: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

---

spring:
  profiles: prod

logging:
  path: /home/depromeet7/logs