spring:
  profiles:
    active: local

password:
  encoder:
    secret: mysecret
    iteration: 33
    keylength: 256

jjwt:
  secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
  expiration: 288000000

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    .: error
    org.springframework: ERROR
    com.warmup.familytalk: INFO

---

spring:
  profiles: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/familytalk
    username: depromeet
    password: pass

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    jdbc:
      lob:
        non_contextual_creation: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

---

spring:
  profiles: prod

logging:
  path: /home/depromeet7/logs

---

spring:
  profiles: test