spring:
  profiles:
    active: local
  main:
    web-application-type: reactive
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

password:
  encoder:
    secret: mysecret
    iteration: 33
    keylength: 256

jjwt:
  secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
  expiration: 28800

server:
  error:
    whitelabel:
      enabled: false
---

spring:
  profiles: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/familytalk
    username: depromeet
    password: pass

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    jdbc:
      lob:
        non_contextual_creation: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

---

spring:
  profiles: prod

logging:
  path: /home/depromeet7/logs